navbar:
  blog_title: 个人记录站点。保存一些文章。
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 100
  slogan:
    text: 这个BLOG看起来很漂亮，希望。
post:
  banner_img: /images/uploads/netlify背景.jpg
  banner_img_height: 70
  default_index_img: /images/uploads/喜报.jpg
archive:
  banner_img: /images/uploads/netlify背景.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/netlify背景.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/netlify背景.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/netlify背景.jpg
  banner_img_height: 80
  subtitle: null
  avatar: /img/avatar.png
  name: Fluid
  intro: An elegant theme for Hexo
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: 暮雨千泷
      intro: 青天白日梦神仙
      link: https://www.myql.xyz
      avatar: https://cdn.jsdelivr.net/gh/leicancun/img@main/images/avatar.webp
